output: "/control/ackermann_cmd"
rate_hz: 50.0
idle_publish_stop: true    # publica stop si ninguna fuente est√° viva

topics:
  - name: "e_stop"
    topic: "/safety/stop_cmd"
    timeout: 0.20
    priority: 100
    shortcircuit: true

  - name: "teleop"
    topic: "/control/ackermann_cmd_mux/input/teleop"
    timeout: 0.50
    priority: 50
    shortcircuit: false

  - name: "navigation"
    topic: "/control/ackermann_cmd_mux/input/navigation"
    timeout: 0.50
    priority: 10
    shortcircuit: false
